'''this is my api'''
from flask import Flask
from argparse import ArgumentParser
from werkzeug.contrib.fixers import ProxyFix
from flask_restplus import Api


def cli():
    # arg parser for the standard anaconda-project options
    parser = ArgumentParser(prog="api",
                            description="API Generated by comatose")
    parser.add_argument('--anaconda-project-host', action='append', default=[],
                        help='Hostname to allow in requests')
    parser.add_argument('--anaconda-project-port', action='store', default=8086, type=int,
                        help='Port to listen on')
    parser.add_argument('--anaconda-project-iframe-hosts',
                        action='append',
                        help='Space-separated hosts which can embed us in an iframe per our Content-Security-Policy')
    parser.add_argument('--anaconda-project-no-browser', action='store_true',
                        default=False,
                        help='Disable opening in a browser')
    parser.add_argument('--anaconda-project-use-xheaders',
                        action='store_true',
                        default=False,
                        help='Trust X-headers from reverse proxy')
    parser.add_argument('--anaconda-project-url-prefix', action='store', default='',
                        help='Prefix in front of urls')
    parser.add_argument('--anaconda-project-address',
                        action='store',
                        default='0.0.0.0',
                        help='IP address the application should listen on.')

    return parser


def run_app(ns):
    api = Api(title='comatose api')
    api.add_namespace(ns)

    app = Flask(__name__)
    api.init_app(app)

    app.config['PREFERRED_URL_SCHEME'] = 'https'

    app.wsgi_app = ProxyFix(app.wsgi_app)

    args = cli().parse_args()
    app.run(host=args.anaconda_project_address, port=args.anaconda_project_port)


if __name__ == '__main__':
    from wrapper import publish

    @publish(['get'])
    def func(a: str, b: int = 10):
        return {'a':a, 'b':b}

    run_app(func)
